---
- name: Using dict2items
  # target_host 来源于命令行
  hosts: "{{ target_host }}"
  # 不需要收集主机信息
  gather_facts: false

  # 任务
  tasks:

    # 旧方法处理字典数据
    - name: with_dict 处理字典数据
      debug:
        msg: "{{ item.key }} -> {{ item.value.ip_address }} 【{{ item.value.role }}】"
      with_dict: "{{ server_configs }}"

    # 新方法处理字典数据1
    - name: loop 处理字典数据1
      debug:
        msg: "{{ item.key }} -> {{ item.value.ip_address }} 【{{ item.value.role }}】"
      # 循环后, 使用dict2items将字典转换为items
      loop: "{{ server_configs | dict2items }}"
      # 添加条件
      when:
        - item.value is mapping
        - item.value.ip_address is defined

    # 新方法处理字典数据2
    - name: loop 处理字典数据2
      debug:
        msg: "{{ item.key }} -> {{ item.value.amount }}"
      loop: "{{ super_fruits | dict2items }}"
    
    # 新方法处理列表数据
    - name: loop 处理列表数据
      debug:
        msg: "{{ item.name }} -> {{ item.groups }}"
      loop: "{{ address_01 }}"

  # 任务需要使用的变量
  vars:
    server_configs:
      web_01:
        ip_address: "10.1.1.50"
        role: "frontend"
      db_01:
        ip_address: "10.1.1.100"
        role: "backend_db"
    super_fruits:
      apples:
        amount: 10
      bananas:
        amount: 20
    address_01:
      - { name: 'testuser1', groups: 'wheel' }
      - { name: 'testuser2', groups: 'root' }