[all:vars]
# 设置当前的环境变量
env=d01

[site_d01:children]
jmo
#oma

# jmo分组
[jmo]
jmo-001 ansible_host=172.22.125.148 ansible_port=9022 ansible_ssh_private_key_file=/home/apluser/.ssh/id_rsa_ubuntu22
jmo-002 ansible_host=192.168.137.129 ansible_ssh_private_key_file=/home/apluser/.ssh/id_rsa_ubuntu24 

[jmo:vars]
ansible_user=apluser
ansible_python_interpreter=/usr/bin/python3

# oma分组
[oma]
oma-001 ansible_host=192.168.3.23 ansible_port=8022

[oma:vars]
ansible_user=u0_a362
ansible_python_interpreter=/data/data/com.termux/files/usr/bin/python
ansible_ssh_private_key_file=/home/apluser/.ssh/id_ed25519_termux
