# ===================== ubuntu分组 =====================
[ubuntu]
# 设置别名 + 设置端口号
# ubuntu_test1 ansible_host=192.168.137.129 ansible_port=22

# ===========================================
# 当使用别名的时候
# host_vars文件夹中的文件名要和机器别名相同
# ===========================================
ubuntu_test1 ansible_host=192.168.137.129 ansible_ssh_private_key_file=/home/apluser/.ssh/id_rsa_ubuntu24
ubuntu_test2 ansible_host=172.22.125.148

[ubuntu:vars]
ansible_user=apluser
ansible_python_interpreter=/usr/bin/python3

# ===================== termux分组 =====================
[termux]
termux_test1 ansible_host=192.168.3.23 ansible_port=8022

[termux:vars]
ansible_user=u0_a362
ansible_python_interpreter=/data/data/com.termux/files/usr/bin/python
ansible_ssh_private_key_file=/home/apluser/.ssh/id_ed25519_termux
